
import AppPackage.AnimationClass;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author suresh
 */
public class playlist extends javax.swing.JFrame {
    
    int xMouse,yMouse,x,y;
    AnimationClass ac=new AnimationClass();
    int rowCount;

    String trackname="null_val",trackdest="null_val";
    int playrow=0;
    int initialplayval=0;
    int pauseValue=0;

   int playingplaylist=-1;
    
    MainClass MC=new MainClass();
    
    public playlist() {
        initComponents();
        animatee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        scrollpane = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        label4 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JLabel();
        wlabel = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panel.setLayout(null);

        label5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close1.png"))); // NOI18N
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label5MouseEntered(evt);
            }
        });
        panel.add(label5);
        label5.setBounds(720, 20, 20, 30);

        tb1.setBackground(new java.awt.Color(102, 102, 102));
        tb1.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        tb1.setForeground(new java.awt.Color(255, 255, 255));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRACK NAME", "TRACK LOCATION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.setGridColor(new java.awt.Color(0, 0, 0));
        tb1.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tb1.setMaximumSize(new java.awt.Dimension(30, 0));
        tb1.setOpaque(false);
        tb1.setRowHeight(30);
        tb1.setSelectionBackground(new java.awt.Color(102, 255, 102));
        tb1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        scrollpane.setViewportView(tb1);

        panel.add(scrollpane);
        scrollpane.setBounds(50, 90, 670, 210);

        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min.png"))); // NOI18N
        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
        });
        panel.add(label4);
        label4.setBounds(693, 28, 20, 16);

        label3.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        label3.setText("MY PLAYLIST");
        panel.add(label3);
        label3.setBounds(210, 20, 340, 30);

        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ggggggg.png"))); // NOI18N
        label2.setText("jLabel2");
        panel.add(label2);
        label2.setBounds(0, -6, 770, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(280, 420, 180, 50);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del1.png"))); // NOI18N
        delete.setToolTipText("Delete from playlist");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteMouseReleased(evt);
            }
        });
        panel.add(delete);
        delete.setBounds(610, 300, 130, 70);

        wlabel.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        panel.add(wlabel);
        wlabel.setBounds(90, 320, 460, 30);

        label1.setBackground(new java.awt.Color(10, 4, 38));
        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Retro Microphone On Fire 3544.jpg"))); // NOI18N
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel.add(label1);
        label1.setBounds(0, 0, 1100, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        xMouse=evt.getX();
        yMouse=evt.getY();
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
        
        
    }//GEN-LAST:event_formMouseDragged

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        this.dispose();
    }//GEN-LAST:event_label5MouseClicked

    private void label5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseEntered
        label5.setBackground(Color.BLACK);
    }//GEN-LAST:event_label5MouseEntered

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
        this.setState(playlist.ICONIFIED);
    }//GEN-LAST:event_label4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser choose=new JFileChooser("C:\\Users\\suresh\\Desktop\\songs");
        FileFilter filter=new FileNameExtensionFilter("Music files","mp3");
        choose.addChoosableFileFilter(filter);
        int val=choose.showOpenDialog(label1);
        
        if(val==JFileChooser.APPROVE_OPTION)
        {
           File myfiles=choose.getSelectedFile();
           String sdest=myfiles+"";
           String sname=myfiles.getName();
           insert_track(sdest,sname);
           
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseReleased

        
    }//GEN-LAST:event_deleteMouseReleased

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
               
        DefaultTableModel mod=(DefaultTableModel)tb1.getModel();
        if(rowCount!=0)
        {
        int srow=tb1.getSelectedRow();
            try {
                System.out.println("play row = "+playrow+" Avail song = "+MC.FIS.available());
                if(mod.getValueAt(srow,0).toString().compareTo(trackname)==0 && MC.FIS.available()!=0)
                {   
                    wlabel.setText("Cannot delete this song coz its playing");
                }
                else
                {   
                    System.out.println("Available song = "+MC.FIS.available()+" srow = "+srow);
                    mod.removeRow(srow);
                    rowCount=mod.getRowCount();
                    wlabel.setText("");
                }   } catch (IOException ex) {
                Logger.getLogger(playlist.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playlist().setVisible(true);
            }
        });
    }

    public void insert_track(String song_path,String song_name)
    {
        DefaultTableModel model=(DefaultTableModel)tb1.getModel();
            String a=song_path;
            String b=song_name;
            model.addRow(new Object[]{b,a});
            rowCount=model.getRowCount();
            System.out.println("Total no of rows = "+rowCount);
    }
    
    /**
     *
     * @throws java.lang.InterruptedException
     */

    public void startplaylist() throws InterruptedException          
    {
        DefaultTableModel model1=(DefaultTableModel)tb1.getModel();
        if(playrow<rowCount)
        {   playrow++;
            if(playrow==rowCount)
            {
               playrow=0; 
            }
            MC.stop();
            trackdest=model1.getValueAt(playrow,1).toString();
            trackname=model1.getValueAt(playrow,0).toString();
            MC.play(trackdest);           
            System.out.println("next = "+playrow);
        }
    }
    
    
  public void backplay()
  {
      
      DefaultTableModel mymodel=(DefaultTableModel)tb1.getModel();
        if(playrow>=0)
        {   
            if(playrow>0)
            {
            playrow--;
            MC.stop();
            trackdest=mymodel.getValueAt(playrow,1).toString();
            trackname=mymodel.getValueAt(playrow,0).toString();
            MC.play(trackdest); 
            }
            else
            {
                playrow=rowCount-1;
                MC.stop();
                trackdest=mymodel.getValueAt(playrow,1).toString();
                trackname=mymodel.getValueAt(playrow,0).toString();
                MC.play(trackdest);
                
            }
            System.out.println("back next = "+playrow);
        }
  }
  
  

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JTable tb1;
    private javax.swing.JLabel wlabel;
    // End of variables declaration//GEN-END:variables

  private void animatee() {
        
        new Thread()
        {
            
            public void run()
            {
                int count=0;
                try
                {
                    
                    while(true)
                    {
                        switch(count)
                        {
                            case 0:
                                     ac.jLabelXLeft(0,-300,20,1,label1);
                                     count=1;
                                     break;
                            case 1: Thread.sleep(300);
                                     ac.jLabelXRight(-300,0,20,1,label1);
                                     count=0;
                                     break;
                        }
                    }
                    
                    
                }catch(Exception e)
                {
                    System.out.println("ERROR!"+e);
                }
            }
            
        }.start();
                
    }
}
